### ISSUE TITLE
No signature found in input row names

### ISSUE THREAD

**Issue by MoMosa-2020** [ebecht/MCPcounter#11]
Hi, 

I'm trying to use MCPcounter on a RNA-seq data from human CRC. the data have been processed using DESeq2 and VST transformed. whenever i try to run the program it gives me the following error:

Error in mMCPcounter.estimate(MCP_geneID1) : 
  No signature found in input row names. Please ensure these are gene symbols.

i have tried borth Entrez IDs and HUGO symbols and always get the same error message.
could anybody help with such issue ?
Thanks a lot
--

> | >
>

**Comment by ebecht** [comment]
Hello,

Could you post ```head(MCP_geneID1)```?

**Comment by MoMosa-2020** [comment]
Hi ebecht, 
it works now. 
thanks anyway for your response!
