### ISSUE TITLE
Error in get("HUGO symbols")

### ISSUE THREAD

**Issue by IrisWong** [ebecht/MCPcounter#13]
Hello @ebecht,

Before I tried to get reulsts on my own microarray data, I've followed the exemplary code to get outcome smoothly. However, after I've loaded a matrix like MCPcounterExampleData, I met "Error in get("HUGO symbols") : object 'HUGO symbols' not found" in use of MCPcounter.estimate function. 

Following is the code.
`library(devtools)`
`library(MCPcounter)`
`data<-read.csv("C:\\Users\\79896\\Desktop\\MCP.csv",header = TRUE,sep = ",",row.names = 1)`
`matrix=as.matrix(data)`
`genes=read.table("C:\\Users\\79896\\Desktop\\genes.txt",header = TRUE,sep = "\t",row.names = 1)`
`result<-MCPcounter.estimate(matrix,featuresType="HUGO_symbols",
                              genes=genes)`
There is a snapshot of MCP.csv.
![image](https://user-images.githubusercontent.com/45477674/74914943-4f922d80-53fe-11ea-91d4-54607fde4887.png)

Frankly I'm a beginner of learning R, owning to this, the way I ask may be disturbing in some degree. If you need more information, I am ready anytime. 

Thanks for your generosity!
Iris

**Comment by ebecht** [comment]
Hello @IrisWong 

I guess that the issue is in `genes`. Could you post `head(genes)` ?
In particular for your use `genes` requires at least two columns, one named `HUGO_symbols` and one named `Cell population`.

Also could you let me know what `class(genes)` returns? It should be `data.frame`

Thanks
Etienne

**Comment by IrisWong** [comment]
Thanks for your prompt reply! @ebecht 

I have checked there is four columns in `genes` and ensured `class(genes)` returning `data.frame`.And then I have another try to run, but still get the same confusing result.
![result for head(genes) and class(genes)](https://user-images.githubusercontent.com/45477674/74998565-0d1b3000-5494-11ea-8cf1-74e123635fe3.jpg)
[genes.txt](https://github.com/ebecht/MCPcounter/files/4233962/genes.txt)

Thanks for your patience,
Iris

**Comment by ebecht** [comment]
Thanks for posting this information,

As you can see the column names in the `genes` data.frame are slightly different from the ones [found here](https://github.com/ebecht/MCPcounter/blob/master/Signatures/genes.txt)

I suggest that you do either of the following:

- Leave the `genes` argument in `MCPcounter.estimate` blank. The default value will automatically pull the gene list I linked above.

or

- If for some reason you want your gene list to be read from your local file, you should
1. make sure that the dots visible in the column names you posted are not present in the file `MCP.csv` itself (so open it with e.g. Microsoft Excel or a text editor and make sure that "HUGO.symbols" is "HUGO symbols" in the file itself, and that "Cell.population" is "Cell population". In the file you linked above, this is the case.
2. When this is done/checked, change
`genes=read.table("C:\\Users\\79896\\Desktop\\genes.txt",header = TRUE,sep = "\t",row.names = 1)`
to
`genes=read.table("C:\\Users\\79896\\Desktop\\genes.txt",header = TRUE,sep = "\t",row.names = 1, check.names = FALSE)`

This should fix your problem

Thank you
Etienne

**Comment by IrisWong** [comment]
I really appreciate your specific reply! 

Although a new erro showed up in first method, which is “schannel: failed to receive handshake, SSL/TLS connection failed”, I am still tring to figure it out by learning [https://github.com/desktop/desktop/issues/2920](url). 

Also, after checking over in the second (self-customized-genes) way, the error is remerging. Quite confused and discouraged. 
![20200223-genes](https://user-images.githubusercontent.com/45477674/75095566-f62e2800-55d0-11ea-96c4-7c069681f7cc.jpg)

Much thanks for your help again,
Iris

**Comment by ebecht** [comment]
@IrisWong programming can be a bit frustrating at first, but the more you do it the easiest it becomes. It's great that you're doing this!

It looks like the `genes` data.frame you posted does not have column names. Maybe `header = TRUE` was forgotten in ` genes=read.table("C:\\Users\\79896\\Desktop\\genes.txt",header = TRUE,sep = "\t",row.names = 1, check.names = FALSE)` ? 

Otherwise, maybe the easiest is to change the column names of the `genes` data.frame after it is loaded.

`colnames(genes) <- c("ENTREZID", "HUGO symbols", "Cell population")`

Then call `MCPcounter.estimate`

**Comment by IrisWong** [comment]
@ebecht 
Finally, the easiest method changing the column names worked! I can't express how thrilled I feel when there are not more errors. 

Please accept my heartfelt thanks for both the heartwarming encouragement and useful helps! 

Gratefully,
Iris

**Comment by ebecht** [comment]
Happy to hear it worked. You're very welcome. Thank you for using our package.

Etienne
