### ISSUE TITLE
object 'missing.populations' not found

### ISSUE THREAD

**Issue by debsXXCIII** [ebecht/MCPcounter#14]
Hi @ebecht 

I am trying to use MCP Counter and I get the following error:

Error in MCPcounter.estimate(data, featuresType = "ENTREZID", genes = genes) : 
  object 'missing.populations' not found

Here are my commands:

data <- read.csv("C:/Users//Documents/MCPCounter/MCP_data.csv",header = TRUE,sep = ",",row.names = 1, check.names = FALSE)

genes=read.table("C:/Users/dguest/Documents/MCPCounter/genes.txt",header = TRUE,sep = "\t",row.names = 1, check.names = FALSE)

result<-MCPcounter.estimate(data, featuresType="ENTREZID", genes=genes)

Please could you let me know how I can debug this?

Many thanks

Deborah

**Comment by ebecht** [comment]
Hi,

Please try:
`result<-MCPcounter.estimate(data, featuresType="ENTREZ_ID", genes=genes)`

Thank you

**Comment by debsXXCIII** [comment]
Hi @ebecht

Unfortunately this still generates the same error, I made sure that the headings had the same spellings. 

Thanks

**Comment by ebecht** [comment]
Hi @debsXXCIII 

What do you mean by "the headings had the same spellings" ? The call should still be using `featuresType="ENTREZ_ID"` even if the corresponding column in the `genes` data.frame is named `"ENTREZID"`

**Comment by ebecht** [comment]
Closing this, feel free to re-open if that issue wasn't solved
