### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by ebecht** [ebecht/MCPcounter#17]
hello, @ebecht 
I used your method: in 22 jan.
but it's doesn't work.
1.install_github("ebecht/MCPcounter",ref="master", subdir="Source")
Skipping install of 'MCPcounter' from a github remote, the SHA1 (8c37884e) has not changed since last install.
  Use `force = TRUE` to force installation
2.install.packages("C:/Users/Administrator/Downloads/ebecht-MCPcounter-8c37884.tar.gz", repos = NULL, type = "source")
Warning in untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
ERROR: cannot extract package from 'C:/Users/Administrator/Downloads/ebecht-MCPcounter-8c37884.tar.gz'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘C:/Users/Administrator/Downloads/ebecht-MCPcounter-8c37884.tar.gz’ had non-zero exit status

_Originally posted by @jianguozhouzunyimedicaluniversity in https://github.com/ebecht/MCPcounter/issues/7#issuecomment-480124185_

**Comment by ebecht** [comment]
hi @jianguozhouzunyimedicaluniversity and @itamuria

Are you two having the exact same issue?

Have you tried using `force = TRUE` in `install_github()` as suggested by the function's execution?

Thanks
Etienne

**Comment by jianguozhouzunyimedicaluniversity** [comment]
> hi @jianguozhouzunyimedicaluniversity and @itamuria
> 
> Are you two having the exact same issue?
> 
> Have you tried using `force = TRUE` in `install_github()` as suggested by the function's execution?
> 
> Thanks
> Etienne

Hello Etienne,
@ebecht  I used anchor tool, https://github.com/jianguozhouzunyimedicaluniversity/immunedeconv, this merge 6 methods.

**Comment by jianguozhouzunyimedicaluniversity** [comment]
https://github.com/jianguozhouzunyimedicaluniversity/immunedeconv <https://github.com/jianguozhouzunyimedicaluniversity/immunedeconv>
 I used this tool.

**Comment by ebecht** [comment]
That's great, i think it's a very interesting package.

If you are having issues installing MCPcounter specifically, can you run:

```
install.packages(c("devtools","curl")) ##Installs devtools and the MCPcounter dependancy 'curl'
library(devtools)
install_github("ebecht/MCPcounter",ref="master", subdir="Source", force = TRUE)
```
