### ISSUE TITLE
 Timeout was reached

### ISSUE THREAD

**Issue by maozdd** [ebecht/MCPcounter#18]
Hello,  I am getting below error when runnig MCPcounter.estimate()

Timeout was reached: [raw.githubusercontent.com] Connection timed out after 10000 milliseconds

Please tell me how to resolve this query.
Thanks

**Comment by ebecht** [comment]
Hi @maozdd 

I suggest that you download locally the tables listing MCP-counter's transcriptomic markers at https://github.com/ebecht/MCPcounter/blob/master/Signatures/genes.txt

Then call `MCPcounter.estimate` with the argument `genes = read.table("path/to/the/downloaded/file",sep="\t",stringsAsFactors=FALSE,header=TRUE,colClasses="character",check.names=FALSE))`

**Comment by maozdd** [comment]
Thank you very much, it worked. @ebecht
