### ISSUE TITLE
T cells v. CD8 T cells v. Cytotoxic lymphocytes

### ISSUE THREAD

**Issue by jlkravitz** [ebecht/MCPcounter#2]
What is the difference between the output of these three? Do `T cells` subsume the latter two? What's the difference between CD8 T cells and cytotoxic lymphocytes? Usually I think of these two as the same.

Also, I just want to confirm that scores are only comparable across samples – that is, is it correct to say that it's not valid to compare two scores within a sample and conclude that a given sample has more cells of type A than type B?

**Comment by ebecht** [comment]
> What is the difference between the output of these three? Do T cells subsume the latter two? What's the difference between CD8 T cells and cytotoxic lymphocytes? Usually I think of these two as the same.

The relationship between cell populations and the metagenes' names is summarized in the Supplementary Figure 1 of our paper. In this case,  T cells will roughly correspond to both CD4+ T cells and CD8+ T cells, Cytotoxic lymphocytes would be mostly CD8+ T cells and NK cells (in addition to gamma-delta T cells and NKT cells which are also cytotoxic lymphocytes). CD8+ T cells are simply CD8+ T cells.

> Also, I just want to confirm that scores are only comparable across samples – that is, is it correct to say that it's not valid to compare two scores within a sample and conclude that a given sample has more cells of type A than type B?

That is correct.
