### ISSUE TITLE
Score of Monocytes and Monocyte/Macrophage

### ISSUE THREAD

**Issue by Disha770** [ebecht/MCPcounter#20]
Hi, 

I am working with MCP- counter for my project and it is providing me with scores for both Monocyte and Monocyte/Macrophages. The scores for both are exactly the same, I looked into the signature genes file which has the marker genes only for Monocytic lineage, Hence I wanted to understand why is the expression of macrophage is shown instead of just Monocytic lineage.

Thank you in advance.

Disha

**Comment by ebecht** [comment]
Hi @Disha770 

If you use the gene signatures we provide MCP-counter should indeed return a score for the Monocytic lineage which includes both Monocytes and Macrophages. Can you provide me with the command you run (the call to `MCPcounter.estimate` ?

Thank you

**Comment by Disha770** [comment]
Hi, 
I have used the same gene signatures that are provided in the MCP-counter and it identifies Monocytes and Monocytes/ Macrophages, Hence I was wondering why it shows me both.

<img width="422" alt="Screenshot 2020-08-13 at 10 22 24" src="https://user-images.githubusercontent.com/65419291/90117470-e35e0a00-dd4e-11ea-9c70-8e8b5cfd2b7d.png">

**Comment by ebecht** [comment]
Could you show the exact call to `MCPcounter.estimate` (the command line, not the result). This does not look like the default list of transcriptomic markers.

Thank you.

**Comment by Disha770** [comment]
Hi, I have used the "immunedeconv" package for MCP counter, which stored the default signature genes from MCP- counter.
res_mcp_counter = deconvolute(average_validation, "mcp_counter")
[genes.txt](https://github.com/ebecht/MCPcounter/files/5078511/genes.txt)

**Comment by ebecht** [comment]
Can you try with the following:
```
library(MCPcounter)
res_mcp_counter = MCPcounter.estimate(average_validation, featuresType = "HUGO_symbols")
```

**Comment by ebecht** [comment]
Since this does not seem to be an issue with the `MCPcounter` package, I am closing the issue.
