### ISSUE TITLE
Terms of use

### ISSUE THREAD

**Issue by ALGW71** [ebecht/MCPcounter#22]
Can this be used as part of an academic industrial collaboration?

This page says it is free to use.
https://github.com/icbi-lab/immunedeconv

This website requests we fill out details to download. And states it is not allowed to be used in any industrial collaboration.
https://cit.ligue-cancer.net/mcp-counter/

There are conflicting statements on the terms of use and I have received no reply when contacting: 
matthieu.collin@inserm-transfert.fr

Please clarify.

**Comment by ebecht** [comment]
Hi @ALGW71,
Sorry about the confusion. Yet it is fine to use, the licence on the repository is GPL-3.

Best,
Etienne

**Comment by ALGW71** [comment]
Hi Etienne,

Many thanks.

Kind Regards,
Alex
