### ISSUE TITLE
question about older version

### ISSUE THREAD

**Issue by Kyeongmi-Lee** [ebecht/MCPcounter#23]
hello. Your tool is very helpful for my analysis. thank you.
but I need the older versions of MCPcounter, older than v1.1.0.
I sent the download request https://cit.ligue-cancer.net/mcp-counter/, but received no reply.
Is there any way to download the previous versions of MCPcounter?
thank you in advance.

**Comment by ebecht** [comment]
Hi @Kyeongmi-Lee 

Sorry about the lack of response, I think that website is deprecated but I don't have the right to remove the page sadly. So thanks for posting on github instead.

We haven't released any earlier version. The earliest we released was 1.1.0 alongside with the publication of our paper (as archived there https://zenodo.org/record/61372)

If you could let me know a little bit more details about why you need an earlier version, maybe I could help you out get what you need!

Best,
Etienne

**Comment by Kyeongmi-Lee** [comment]
Hello, thank you for your reply.
I'm writing a paper about drug prediction algorithm and your MCPcounter score was used as input features.
So I have to write the version I used to analyze in my paper.

The problem is that I have upgraded the MCPcounter R library because of a new project, so I don't know which version I used.
I probably used MCPcounter around May of last year.
I tested MCPcounter v1.1.0, and the endothelial cell score result is slightly different from the results I used in the paper.
So I need the older version of MCPcounter, older than v1.1.0 to find the version I was using.

thank you in advance.

**Comment by ebecht** [comment]
Thanks for the explanations,

We haven't released a new version for a few years but there was a small update last year that updated some gene symbols. These were indeed endothelial cell markers so I think that would explain your discrepancy.

You can download the old gene list [here](https://github.com/ebecht/MCPcounter/blob/468c3a32b8e27b9611d0a98497b7a918c27da34b/Signatures/genes.txt), read it into R and pass the result to `MCPcounter.estimate()` with the argument `genes=read.table("path/to/the/downloaded/file.txt", sep="\t", stringsAsFactors=FALSE, header=TRUE, colClasses="character", check.names=FALSE)`

Hopefully that will fix your issue!
I am sorry about the confusion in version numbers. So to clarify, in the methods of your paper you should mention version 1.1.0 and the list of genes in this [commit](https://github.com/ebecht/MCPcounter/commit/8c37884e3fae41b4e872f86bac1061150c6e3c48).

Best,
Etienne

**Comment by Kyeongmi-Lee** [comment]
Hello, thanks for the reply.

I downloaded the old gene list you gave me and checked the same results as before. Thank you. 
And I have one question, I reinstalled the mcpcounter using the code you gave me in the commit and checked the gene list with `genes=read.table(curl("http://raw.githubusercontent.com/ebecht/MCPcounter/master/Signatures/genes.txt"),sep="\t",stringsAsFactors=FALSE,header=TRUE,colClasses="character",check.names=FALSE)` and it is different from the old gene list.

Is it ok to mention only version 1.1.0 in the paper? or is there any way to mention the old gene list?
Thank you in advance.

**Comment by ebecht** [comment]
To clarify, these are the same genes, but the HUGO committee that gives names to genes sometimes changes the gene symbols. So the genes are the same but their symbols have changed which can lead to some confusion. It is usually less ambiguous to rely on ENTREZID or ENSEMBLID for that reason. 

I think for the methods it should be enough to state that you used version 1.1.0.
You can publish your code if you want to make your paper easier to reproduce, where you could explicitly point towards the non-updated gene list.

Best,
Etienne

**Comment by Kyeongmi-Lee** [comment]
Hello. 
I'll just mention the version information for now.
Thank you very much.
