### ISSUE TITLE
Confusion about the result

### ISSUE THREAD

**Issue by leleye** [ebecht/MCPcounter#29]
#@Hi ,
    I perform MCPcounter analyses on BRCA and OV RNASeq data from TCGA these days. It confuses me when the results are influenced by the type of input data (count, log2(count+1), scale(count), fpkm, tpm). Also, when I run EPIC (another method to predict immune cells, https://github.com/GfellerLab/EPIC), the results of these two methods have high correlation in pearson/spearman analysis. I’m wondering if there is some settings I should be careful with?

I‘m eagerly waiting for your reply，thanks！

**Comment by ebecht** [comment]
Hi @leleye 

MCPcounter should be ran on log(fpkm + 1) or log(tpm +1). Non-log data is not advised due to high variance, and counts are influenced by per-sample sequencing depth. 

Etienne

**Comment by leleye** [comment]
Hi Etienne,
Thanks for your input!! 
Can you as well take a look at the other part of the previous question :
”when I run EPIC method for **CAF/fibroblast**, the result has high correlation with result from MCPcounter in pearson/spearman analysis”  which has significant differ with a previous study (Risk Signature of Cancer-Associated Fibroblast–Secreted Cytokines Associates With Clinical Outcomes of Breast Cancer).
I attached main code and screenshots: 
`results <- MCPcounter.estimate( 
  log2(1+dat_input),
  featuresType='HUGO_symbols', 
  probesets=probesets1,
  genes=genes1)

result <- EPIC(dat_input, reference="TRef")

xCell<- xCellAnalysis(dat_input, rnaseq = T) 
ggplot(cells, aes(EPIC, MCP))
(Other parameters are default)`
<img width="329" alt="1" src="https://user-images.githubusercontent.com/40029442/169353472-b9f13486-dc3e-4b8a-b08c-43af05350755.png">
<img width="329" alt="2" src="https://user-images.githubusercontent.com/40029442/169353544-116c4795-39d0-4ba8-abfd-c9708521ffb2.png">

<img width="1003" alt="WechatIMG109" src="https://user-images.githubusercontent.com/40029442/169436702-0ebed672-eb64-48a0-9f52-2a00f6b80b4b.png">
(From the previous study)
Is that looking good to you ? Please let me know if I’m doing something wrong here. 
Thank you !

**Comment by ebecht** [comment]
I haven't read this study in details but I think I would rather find reassuring that multiple methods agree ! 

In that previous study, I am quite surprised by the y-scale for the MCPcounter graphs, I wonder whether they did log-transform the data.

**Comment by leleye** [comment]
Hi Etienne,
 Thanks for your reply！ I really appreciate your time！

Best regards,
Emily
