### ISSUE TITLE
Can you provide sample input format?

### ISSUE THREAD

**Issue by venkataddala** [ebecht/MCPcounter#3]

**Comment by ebecht** [comment]
The input format is an expression matrix with features in rows and samples in columns. Features are either affymetrix 133+2 prob_ids, HUGO gene symbols or ENTREZ identifiers. You can check the object `MCPcounterExampleData` after loading the package (`library(MCPcounter)`) to see an example input. You may also want to read `?MCPcounter.estimate` where a use case is illustrated
