### ISSUE TITLE
webMCP-counter vs R MCP-counter

### ISSUE THREAD

**Issue by rjoana1** [ebecht/MCPcounter#32]
Hello! Thanks for this tool.
I've used the same gene_expression_matrix for both webMCP-counter and R MCP-counter.
On the first I get a results score matriz with all scores except fibroblasts.

Using the R version:

probesets=read.table(curl("http://raw.githubusercontent.com/ebecht/MCPcounter/master/Signatures/probesets.txt"),sep="\t",stringsAsFactors=FALSE,colClasses="character")

genes=read.table(curl("http://raw.githubusercontent.com/ebecht/MCPcounter/master/Signatures/genes.txt"),sep="\t",stringsAsFactors=FALSE,header=TRUE,colClasses="character",check.names=FALSE)

result_mcp_count=MCPcounter.estimate(gene_expression_matrix)

I get:
Warning: Found no markers for population(s): T cells, CD8 T cells, Cytotoxic lymphocytes, NK cells, B lineage, Monocytic lineage, Myeloid dendritic cells, Neutrophils, Endothelial cells, Fibroblasts

Are the parameters the same?
I thank you in advance for you answer.

**Comment by rjoana1** [comment]
I was runing this code in a desktop I usually do not use (different R versions, different keyboard settings). I run the same code on my normal computer and it worked fine.

I'm closing the comment.

**Comment by FPetitprez** [comment]
Thanks for this comment! We'll add the R version and session info in webMCP-counter to avoid confusion in the future.
