### ISSUE TITLE
HUGO symbols not found

### ISSUE THREAD

**Issue by DamarisDeng** [ebecht/MCPcounter#35]
Hi! Thanks for providing this package!
![image](https://github.com/ebecht/MCPcounter/assets/80014460/6b5ff72a-1c7a-4479-ac08-114fec59292c)
When I use the command 
```R
MCPcounter.estimate(RNASeq_lihc2, featuresType = "HUGO_symbols", 
                    probesets=probesets,
                    genes=genes)
```
It says `Error in get("HUGO symbols") : object 'HUGO symbols' not found`.
How to solve this?

**Comment by ebecht** [comment]
Hello,

Could you print `head(genes)` ? That should be where the problem comes from.

Etienne

**Comment by DamarisDeng** [comment]
![image](https://github.com/ebecht/MCPcounter/assets/80014460/15115f14-2f34-4692-b62f-1cb35b8b5dbf)

**Comment by ebecht** [comment]
I think that you need to add the argument `check.names = FALSE` in the call to `read.table()` when you define `genes`

**Comment by DamarisDeng** [comment]
Thanks for your solution!
![image](https://github.com/ebecht/MCPcounter/assets/80014460/3dd8b039-9450-4bfe-ac7c-7819c95b2159)
There's no error anymore, but I got a 0 x 0 matrix.

**Comment by ebecht** [comment]
Could you show `RNASeq_lihc2[1:5, 1:5]` ? Probably a problem with the `row.names` from that object that are not matching HUGO_symbols

**Comment by DamarisDeng** [comment]
Oh thank you so much! I got it! My `RNASeq_lihc2` is a tibble and the operation `rownames(RNASeq_lihc2)` failed. Now I can get the result by converting `RNASeq_lihc2` to a dataframe.

Thank you so much for your patient reply.
