### ISSUE TITLE
Can I add other immune cell marker genes?

### ISSUE THREAD

**Issue by YiweiNiu** [ebecht/MCPcounter#5]
Hi,

I want to use `MCPcounter` to infer other immunce cell subpopulations not included by `MCPcounter`. Can I add other markers to the current signature gene list?

Yiwei Niu

**Comment by ebecht** [comment]
Hello,

Yes you can add your own gene signatures. For this you can for instance download the tabulated signatures from this repository (under the _Signatures_ folder), and add additional lines corresponding to your own signatures. Then you can use your local table as the `genes` or `probesets` argument of `MCPcounter.estimate`

However the algorithm we use for summarizing gene sets if very simple. The relevance of our approach is the stringency in the selection procedure for marker genes. So if you add additional signatures using the method described above, please refrain from calling them MCPcounter scores.

Thank you,

**Comment by YiweiNiu** [comment]
Thank you for your quick reply!

>So if you add additional signatures using the method described above, please refrain from calling them MCPcounter scores.

Could you please explain it in more detail?

To my understanding, the key of `MCPcounter` is to select Transciptome Markers (TM) in which genes "expressed in one and only one cell population and whose expression shows little variation within the population of interest". And then "MCP-counter scores were defined as the log2 average expression of the TM for each population". So if I add more genes to the current gene list, I have to assure that they accord the criterion of TM. Then I can use the final socre like the current ones. Is that right?

I don't know how the TM differ from commonly referred "immune cell markers". I think the ways to select them are similar, such as list used in [Davoli et al. 2017](http://science.sciencemag.org/content/355/6322/eaaf8399) and list used in [Charoentong et al. 2017](https://www.sciencedirect.com/science/article/pii/S2211124716317090). My point is: these genes are all specifically expressed in specific cell type. Considering the way `MCPcounter`  calculates the score, can I use these gene list for `MCPcounter`? I want to infer other cell types that have not been covered by `MCPcounter`, such as macrophages.

Sorry if the question is basic or if my understanding is biased. Thank you in advance!
