### ISSUE TITLE
Problems with gene signature

### ISSUE THREAD

**Issue by jackadsad** [ebecht/MCPcounter#9]
Hi~
MCPcounter is really a perfect R package. 
But I have a problem. In the file named 'gene.txt', MGC40069 (ENTREZID:348035) can not be found in data from TCGA. 
Information on MGC40069 even can't be found on Genecards.
What should i do with it? Can i delete   MGC40069 from the gene.txt?

**Comment by ebecht** [comment]
Hi @jackadsad 

If a gene is not found in your input expression matrix, it will automatically be ignored. So do not worry if this feature is absent from your data. You can remove it from the gene.txt table but that will not affect your analysis in any way.

If you simply do not trust this is a genuine marker, here's the expression data from the discovery series (which I find convincing). If you prefer to remove the gene anyway, you can do so as long as you make that clear in your Methods if relevant.
![243602_at](https://user-images.githubusercontent.com/21232307/52082812-a35f7980-2552-11e9-8a38-ea69228e6859.png)

I hope that answered your question,
Best
